### PR TITLE
Add some apps

### PR DESCRIPTION
**Pull request by matteodiga**
Add following apps:
- vim_current_word
- vim-airline
- markdown-preview.nvim
- tmux-pomodoro-plus
- nerdtree
- ale

### CODE REVIEW

**Comment by toolleeo** [comment]
Thanks for the contribution.
I had to remove some items, though.
Despite I also am a big fan of vim/nvim, this list is not about plugins, but deals with standalone programs/tools.

**Comment by matteodiga** [comment]
Sure, no problem.
By the way I listed that plugins because I see some are already in (powerline and Org mode).

**Comment by toolleeo** [comment]
Thanks for pointing that out.
Org mode is there since the very early version of the list, and in fact I agree that, as a  pure plugin, it should not be included.
Whereas powerline can also be used outside vim, e.g., in a terminal.

**Comment by matteodiga** [comment]
Understood, that was just to clarify the reason behind my additions.

Thanks, and good afternon prof :)

**Pull request merged**
