### PR TITLE
added tab-pal

### PR DESCRIPTION
**Pull request by ben-n93**
added tab-pal TUI to apps.csv

### CODE REVIEW

**Comment by ccoVeille** [comment]
See #80

**Comment by toolleeo** [comment]
Hello, thanks for the contribution: nice tool.
I can not merge your pull request since the diff says that you changed the whole document.
You probably added a spurious column in the CSV, which added a comma to every line in the file.

Could you please make a suitable commit and re-do the pull request?

If you prefer, I can just add your line to the CSV myself, but in this case you would lose the contribution to the project.

**Comment by ben-n93** [comment]
> Hello, thanks for the contribution: nice tool.
> 
> I can not merge your pull request since the diff says that you changed the whole document.
> 
> You probably added a spurious column in the CSV, which added a comma to every line in the file.
> 
> 
> 
> Could you please make a suitable commit and re-do the pull request?
> 
> 
> 
> If you prefer, I can just add your line to the CSV myself, but in this case you would lose the contribution to the project.

Oh that's fine, if you can add it yourself I'd greatly appreciate it!

Thank you!

**Comment by toolleeo** [comment]
I added the tool. Thanks again.

**Pull request closed without merging**
